name: Go CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -coverprofile=coverage.out -v

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out

  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build application
        run: go build -o app ./cmd/main.go

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: app

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: app-binary
          path: .

      - name: Set up SSH keys with ssh-agent
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Start Deployment
        run: |
          echo "Starting deployment..."
          
          # SSH into the server, pull latest changes, build, and test
          ssh -i ~/.ssh/id_rsa $USERNAME@$SERVER_IP << 'EOF'
            set -e
            echo "Navigating to the project directory..."
            cd /home/ubuntu/CI-CD-with-Unit-testing

            # Pull the latest code and install dependencies
            echo "Pulling latest code..."
            git pull origin main
            echo "Running go mod tidy..."
            go mod tidy
            echo "Building the app..."
            go build -o app ./cmd/main.go

            # Run tests on the server
            echo "Running tests on the server..."
            go test ./... -v

            # Stop the running app (if any)
            echo "Stopping the app..."
            sudo systemctl stop app || echo "Service not running"
          EOF

      - name: Deploy to Server
        run: |
          echo "Deploying new binary..."
          scp app $USERNAME@$SERVER_IP:/home/ubuntu/app

          # Restart the app on the server
          echo "Starting the app..."
          ssh -i ~/.ssh/id_rsa $USERNAME@$SERVER_IP "sudo systemctl start app"

      - name: Verify Deployment
        run: ssh -i ~/.ssh/id_rsa $USERNAME@$SERVER_IP "systemctl status app --no-pager"
