name: Go CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21  

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -coverprofile=coverage.out -v

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out

  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build application
        run: go build -o app ./cmd/main.go

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: app

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: app-binary
          path: .

      - name: List downloaded artifacts
        run: ls -l

      - name: Check if environment variables are set
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          if [ -z "${{ secrets.SERVER_IP }}" ]; then
            echo "SERVER_IP environment variable is not set. Exiting."
            exit 1
          fi
          if [ -z "${{ secrets.SERVER_USER }}" ]; then
            echo "SERVER_USER environment variable is not set. Exiting."
            exit 1
          fi
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "SSH_PRIVATE_KEY environment variable is not set. Exiting."
            exit 1
          fi

      - name: Add server to known hosts
        run: |
          echo "Adding server to known hosts..."
          mkdir -p ~/.ssh
          if ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts; then
            echo "Server SSH key added to known hosts."
          else
            echo "Failed to add SSH key for $SERVER_IP."
            exit 1
          fi
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USER }}
        run: |
          echo "Starting deployment..."

          # Ensure SSH private key is available
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Testing SSH connection..."
          # Test SSH connection
          ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa $USERNAME@$SERVER_IP "echo SSH connection established"

          echo "Stopping the app and removing the old binary..."
          # If the connection is successful, stop the app, remove the old binary
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USERNAME@$SERVER_IP "sudo systemctl stop myapp && rm -f /home/$USERNAME/app && exit"

          echo "Copying new binary to the server..."
          # Copy the new binary
          scp app $USERNAME@$SERVER_IP:/home/$USERNAME/app

          echo "Starting the app..."
          # Start the app
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USERNAME@$SERVER_IP "sudo systemctl start myapp"

      - name: Verify Deployment Status
        run: |
          echo "Verifying deployment..."
          # Check if the app is running
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USERNAME@$SERVER_IP "systemctl status myapp"
